department/urls.py
from django.urls import path
from department import views

app_name = 'departments'
urlpatterns = [
    path('lista/', views.DepartmentListView.as_view(), name='department_list'),
    path('adicionar/', views.DepartmentCreateView.as_view(),
         name='department_create'),
    path('detalhes/<int:pk>', views.DepartmentEditView.as_view(),
         name='department_edit'),
    path('editar/<int:pk>', views.DepartmentDetailView.as_view(),
         name='department_detail'),
    path('deletar/<int:pk>', views.DepartmentDeleteView.as_view(),
         name='department_delete')
]

drogo/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('ip.urls', namespace='ip')),
]

drogon/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('equipamentos/', include('equipments.urls', namespace='equipments')),
    path('departamentos/', include('department.urls', namespace='departments')),
    path('relatorios/', include('reports.urls', namespace='reports')),
    path('', include('dashboard.urls', namespace='dashboard')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ip/urls.py
from django.urls import path
from ip import views

app_name = 'ip'
urlpatterns = [
    path('ip_ativos/', views.IpListView.as_view(), name='active_list'),
    path('ip_inativos/', views.disabled_IP_list, name='disable_list'),
    path('detalhes/<int:pk>/', views.IpDetailView.as_view(), name='detail_ip'),
    path('cadastrar/', views.register_ip, name='register'),
    path('deletar/<int:pk>', views.IpDeleteView.as_view(), name='delete'),
    path('editar/<int:pk>', views.IpUpdateView.as_view(), name='edit'),

    # Department
    path('equipamentos/', views.ElectronicEquipmentListView.as_view(), name='equipments'),
    path('equipamentos/cadastrar/', views.ElectronicEquipmentCreateView.as_view(), name='equipments_create'),
    path('equipamentos/<int:pk>', views.ElectronicEquipmentEditView.as_view(), name='equipments_edit'),
]

department/models.py
from django.db import models


class Base(models.Model):
    register_in = models.DateTimeField(auto_now_add=True)
    updated_in = models.DateTimeField(auto_now=True)
    activated = models.BooleanField(default=True, verbose_name='Ativo')

    class Meta:
        abstract = True


class Department(Base):
    department = models.CharField(max_length=80, verbose_name='Departamento')
    supervisor = models.CharField(max_length=100, verbose_name='Surpervisor')

    def __str__(self):
        return self.department

    def get_absolute_url(self):
        from django.urls import reverse
        return reverse('departments:department_list')

    class Meta:
        verbose_name = 'Departamento'
        verbose_name_plural = 'Departamentos'

department/views.py
from django.urls.base import reverse_lazy
import department
from django.shortcuts import render
from django.views import generic
from department.models import Department


class DepartmentListView(generic.ListView):
    model = Department
    template_name = 'department_list.html'
    context_object_name = 'departments'


class DepartmentCreateView(generic.CreateView):
    model = Department
    template_name = 'department_create_update.html'
    fields = '__all__'


class DepartmentDetailView(generic.DetailView):
    model = Department
    context_object_name = 'department'
    template_name = 'department_detail.html'


class DepartmentEditView(generic.UpdateView):
    model = Department
    template_name = 'department_create_update.html'
    fields = '__all__'


class DepartmentDeleteView(generic.DeleteView):
    model = Department
    template_name = 'department_delete.html'
    context_object_name = 'department'
    success_url = reverse_lazy('departments:department_list')

department/templates/department_create.html
{% extends 'base.html' %}
{% load bootstrap5 %}
{% block content %}
<form method="post" class="uniForm">
    {% csrf_token %}
    {% bootstrap_form form %}
    <button type="submit" class="btn btn-outline-primary">Confirmar</button>
    <a href="{% url 'departments:department_list'%}" class="btn btn-outline-danger">Cancelar</a>
</form>
{% endblock content %}

department/templates/department_create_update.html
{% extends 'base.html' %}
{% load bootstrap5 %}
{% block content %}
<form method="post" class="uniForm">
    {% csrf_token %}
    {% bootstrap_form form %}
    <button type="submit" class="btn btn-outline-primary">Confirmar</button>
    <a href="{% url 'departments:department_list'%}" class="btn btn-outline-danger">Cancelar</a>
</form>
{% endblock content %}

department/templates/department_delete.html
{% extends 'base.html'%}
{% block content %}
<form method="post">
    {% csrf_token %}
    <div class="alert alert-danger d-flex align-items-center" role="alert">
        <i class="fas fa-exclamation-triangle text-warning m-2 fa-2x"></i>
        <div>
            <p>Tem certeza que deseja deletar o departamento: <span class="fw-bold">{{department.department}}</span>?
            </p>
        </div>
    </div>
    <button type="submit" class="btn btn-outline-primary">Confirmar</button>
    <a href="{% url 'departments:department_list' %}" class="btn btn-outline-danger">Cancelar</a>
</form>
{% endblock content %}

department/templates/department_detail.html
{% extends 'base.html' %}
{% block content %}
<table class="table table-bordered text-center">
    <thead>
    <tr>
        <th scope="col">Departamento</th>
        <th scope="col">Supervisor</th>
        <th scope="col">Criado</th>
        <th scope="col">Atualizado</th>
        <th scope="col">Status</th>
    </tr>
    </thead>
    <tbody>
    <tr>
        <th scope="row">{{department.department}}</th>
        <td>{{department.supervisor}}</td>
        <td>{{ department.register_in|date}}</td>
        <td>{{department.updated_in|date}}</td>
        {%if department.activated %}
        <td>Ativo</td>
        {% else %}
        <td>Inativo</td>
        {% endif %}
    </tr>
    </tbody>
</table>
<a href="{% url 'departments:department_edit' department.pk %}" type="button" class="btn btn-outline-warning">Editar</a>
<a href="{% url 'departments:department_list' %}" class="btn btn-outline-primary">Voltar</a>
{% endblock content %}

department/templates/department_list.html
{% extends 'base.html' %}
{% block content %}
<table class="table table-bordered text-center">
    <div class="btn-group mb-2" role="group">
        <a href="{% url 'departments:department_create' %}" type="button" class="btn btn-primary"><i
                class="fas fa-plus"></i>Adicionar</a>
    </div>
    <thead>
        <tr>
            <th scope="col">ID</th>
            <th scope="col">Departamento</th>
            <th scope="col">Supervisor</th>
            <th scope="col">Criado</th>
            <th scope="col">Atualizado</th>
            <th scope="col">Status</th>
            <th scope="col">Ação</th>
        </tr>
    </thead>
    <tbody>
        {% for department in departments %}
        <tr>
            <th scope="row">{{department.id}}</th>
            <td>{{department.department}}</td>
            <td>{{department.supervisor}}</td>
            <td>{{department.register_in|date}}</td>
            <td>{{department.updated_in|date}}</td>
            {% if department.activated %}
            <td scope="row">Ativo</td>
            {% else %}
            <td scope="row">Inativo</td>
            {% endif %}
            <td>
                <div class="btn-group" role="group" aria-label="Basic example">
                    <a href="{% url 'departments:department_detail' department.pk %}" type="button"
                        class="btn btn-success"><i class="fas fa-eye"></i></a>
                    <a href="{% url 'departments:department_edit' department.pk %}" type="button"
                        class="btn btn-primary"><i class="fas fa-edit"></i></a>
                    <a href="{% url 'departments:department_delete' department.pk %}" type="button"
                        class="btn btn-danger"><i class="fas fa-trash-alt"></i></a>
                </div>
            </td>
        </tr>
        {% endfor %}
    </tbody>
</table>
{% endblock content %}