dashboard/urls.py
from django.urls import path
from . import views

app_name = 'dashboard'
urlpatterns = [
    path('', views.DashboardView.as_view(), name='dashboard'),
]

department/urls.py
from django.urls import path
from department import views

app_name = 'departments'
urlpatterns = [
    path('lista/', views.DepartmentListView.as_view(), name='department_list'),
    path('adicionar/', views.DepartmentCreateView.as_view(),
         name='department_create'),
    path('detalhes/<int:pk>', views.DepartmentEditView.as_view(),
         name='department_edit'),
    path('editar/<int:pk>', views.DepartmentDetailView.as_view(),
         name='department_detail'),
    path('deletar/<int:pk>', views.DepartmentDeleteView.as_view(),
         name='department_delete')
]

drogo/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('ip.urls', namespace='ip')),
]

drogon/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('equipamentos/', include('equipments.urls', namespace='equipments')),
    path('departamentos/', include('department.urls', namespace='departments')),
    path('relatorios/', include('reports.urls', namespace='reports')),
    path('', include('dashboard.urls', namespace='dashboard')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

equipments/urls.py
from django.urls import path
from equipments import views

app_name = 'ip'
urlpatterns = [
    path('ip/', views.list_all_ip, name='list_all'),
    path('ip/ativos/', views.IpListView.as_view(), name='active_list'),
    path('ip/inativos/', views.disabled_IP_list, name='disable_list'),
    path('detalhes/<int:pk>/', views.IpDetailView.as_view(), name='detail_ip'),
    path('cadastrar/', views.register_ip, name='register'),
    path('deletar/<int:pk>', views.IpDeleteView.as_view(), name='delete'),
    path('editar/<int:pk>', views.IpUpdateView.as_view(), name='edit'),

    # Department
    path('lista/', views.ElectronicEquipmentListView.as_view(), name='equipments'),
    path('equipamentos/cadastrar/', views.ElectronicEquipmentCreateView.as_view(), name='equipments_create'),
    path('equipamentos/<int:pk>', views.ElectronicEquipmentEditView.as_view(), name='equipments_edit'),
    path('equipamentos/deletar/<int:pk>', views.ElectronicEquipmentDeleteView.as_view(), name='equipments_delete'),
    path('equipamentos/detalhes/<int:pk>', views.ElectronicEquipmentDetailView.as_view(), name='equipments_detail'),
]

ip/urls.py
from django.urls import path
from ip import views

app_name = 'ip'
urlpatterns = [
    path('ip_ativos/', views.IpListView.as_view(), name='active_list'),
    path('ip_inativos/', views.disabled_IP_list, name='disable_list'),
    path('detalhes/<int:pk>/', views.IpDetailView.as_view(), name='detail_ip'),
    path('cadastrar/', views.register_ip, name='register'),
    path('deletar/<int:pk>', views.IpDeleteView.as_view(), name='delete'),
    path('editar/<int:pk>', views.IpUpdateView.as_view(), name='edit'),

    # Department
    path('equipamentos/', views.ElectronicEquipmentListView.as_view(), name='equipments'),
    path('equipamentos/cadastrar/', views.ElectronicEquipmentCreateView.as_view(), name='equipments_create'),
    path('equipamentos/<int:pk>', views.ElectronicEquipmentEditView.as_view(), name='equipments_edit'),
]

reports/urls.py
from django.urls import path
from reports import views

app_name = 'reports'
urlpatterns = [
    path('', views.reports, name='report_list'),
]

templates/includes/head.html
{% load static %}
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.3/css/all.css"
      integrity="sha384-SZXxX4whJ79/gErwcOYf+zWLeJdY/qpuqC4cAa9rOGUstPomtqpuNWT9wdPEn2fk" crossorigin="anonymous">
<!-- Bootstrap CSS -->
<link rel="stylesheet" href="{% static 'css/site.css'%}">
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-F3w7mX95PdgyTmZZMECAngseQB83DfGTowi0iMjiWaeVhAn4FJkqJByhZMI3AhiU" crossorigin="anonymous">

templates/includes/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-dark">
    <div class="container-fluid">
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item dropdown btn btn-light">
                    <a class="navbar-brand" href="{% url 'dashboard:dashboard' %}"><i class="fas fa-tachometer-alt"></i>Dashboard</a>
                </li>
                <li class="nav-item dropdown btn btn-light">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownIP" role="button"
                       data-bs-toggle="dropdown" aria-expanded="false">
                        <i class="fas fa-wifi"></i>IP
                    </a>
                    <ul class="dropdown-menu" aria-labelledby="navbarDropdownIP">
                        <li>
                            <a class="dropdown-item" href="{% url 'ip:register' %}"><i class="fas fa-angle-right"></i>Adicionar</a>
                        </li>
                        <li><a class="dropdown-item" href="{% url 'ip:list_all' %}"><i
                                class="fas fa-angle-right"></i>Listar Todos</a></li>
                        <li><a class="dropdown-item" href="{% url 'ip:active_list' %}"><i
                                class="fas fa-angle-right"></i>Listar Ativos</a></li>
                        <li><a class="dropdown-item" href="{% url 'ip:disable_list' %}"><i
                                class="fas fa-angle-right"></i>Listar Inativos</a></li>
                    </ul>
                </li>
                <li class="nav-item dropdown btn btn-light">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownEquipment" role="button"
                       data-bs-toggle="dropdown" aria-expanded="false"><i class="fas fa-print"></i>Equipamentos
                    </a>
                    <ul class="dropdown-menu" aria-labelledby="navbarDropdownEquipment">
                        <li><a class="dropdown-item" href="{% url 'ip:equipments_create'%}"><i
                                class="fas fa-angle-right"></i>Adicionar</a>
                        </li>
                        <li><a class="dropdown-item" href="{% url 'ip:equipments' %}"><i
                                class="fas fa-angle-right"></i>Listar Todos</a></li>
                    </ul>
                </li>
                <li class="nav-item dropdown btn btn-light">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownDepartment" role="button"
                       data-bs-toggle="dropdown" aria-expanded="false"><i class="fas fa-laptop-house"></i>Departamentos
                    </a>
                    <ul class="dropdown-menu" aria-labelledby="navbarDropdownDepartment">
                        <li><a class="dropdown-item" href="{% url 'departments:department_create'%}"><i
                                class="fas fa-angle-right"></i>Adicionar</a>
                        </li>
                        <li><a class="dropdown-item" href="{% url 'departments:department_list'%}"><i
                                class="fas fa-angle-right"></i>Listar Todos</a></li>
                    </ul>
                </li>
                <li class="nav-item btn btn-warning">
                    <a class="navbar-brand" href="{% url 'reports:report_list' %}">
                        <i class="fas fa-file-pdf"></i>Gerar Relatório</a>
                </li>
            </ul>
        </div>
    </div>
</nav>