drogo/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('ip.urls', namespace='ip')),
]

drogon/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('equipamentos/', include('equipments.urls', namespace='equipments')),
    path('departamentos/', include('department.urls', namespace='departments')),
    path('relatorios/', include('reports.urls', namespace='reports')),
    path('', include('dashboard.urls', namespace='dashboard')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

equipments/urls.py
from django.urls import path
from equipments import views

app_name = 'ip'
urlpatterns = [
    path('ip/', views.list_all_ip, name='list_all'),
    path('ip/ativos/', views.IpListView.as_view(), name='active_list'),
    path('ip/inativos/', views.disabled_IP_list, name='disable_list'),
    path('detalhes/<int:pk>/', views.IpDetailView.as_view(), name='detail_ip'),
    path('cadastrar/', views.register_ip, name='register'),
    path('deletar/<int:pk>', views.IpDeleteView.as_view(), name='delete'),
    path('editar/<int:pk>', views.IpUpdateView.as_view(), name='edit'),

    # Department
    path('lista/', views.ElectronicEquipmentListView.as_view(), name='equipments'),
    path('equipamentos/cadastrar/', views.ElectronicEquipmentCreateView.as_view(), name='equipments_create'),
    path('equipamentos/<int:pk>', views.ElectronicEquipmentEditView.as_view(), name='equipments_edit'),
    path('equipamentos/deletar/<int:pk>', views.ElectronicEquipmentDeleteView.as_view(), name='equipments_delete'),
    path('equipamentos/detalhes/<int:pk>', views.ElectronicEquipmentDetailView.as_view(), name='equipments_detail'),
]

ip/urls.py
from django.urls import path
from ip import views

app_name = 'ip'
urlpatterns = [
    path('ip_ativos/', views.IpListView.as_view(), name='active_list'),
    path('ip_inativos/', views.disabled_IP_list, name='disable_list'),
    path('detalhes/<int:pk>/', views.IpDetailView.as_view(), name='detail_ip'),
    path('cadastrar/', views.register_ip, name='register'),
    path('deletar/<int:pk>', views.IpDeleteView.as_view(), name='delete'),
    path('editar/<int:pk>', views.IpUpdateView.as_view(), name='edit'),

    # Department
    path('equipamentos/', views.ElectronicEquipmentListView.as_view(), name='equipments'),
    path('equipamentos/cadastrar/', views.ElectronicEquipmentCreateView.as_view(), name='equipments_create'),
    path('equipamentos/<int:pk>', views.ElectronicEquipmentEditView.as_view(), name='equipments_edit'),
]

equipments/models.py
from django.db import models

from department.models import Department

EQUIPMENT_TYPE_CHOICES = (
    ('TV', 'TV'),
    ('DESKTOP', 'DESKTOP'),
    ('NOTEBOOK', 'NOTEBOOK'),
    ('SOM', 'SOM'),
    ('ROTEADOR', 'ROTEADOR'),
    ('CÀMERA', 'CÂMERA'),
    ('IMPRESSORA', 'IMPRESSORA'),
    ('OUTROS', 'OUTROS'),
)


class Base(models.Model):
    register_in = models.DateTimeField(auto_now_add=True)
    updated_in = models.DateTimeField(auto_now=True)
    activated = models.BooleanField(default=True, verbose_name='Ativo')

    class Meta:
        abstract = True


class IP(Base):
    ips_address = models.GenericIPAddressField(unique=True, protocol='IPv4', verbose_name='Endereço IP')

    def get_absolute_url(self):
        from django.urls import reverse
        return reverse('ip:detail_ip', kwargs={'pk': self.pk})

    def __str__(self):
        return self.ips_address

    class Meta:
        verbose_name = 'Endereço IP'
        verbose_name_plural = 'Endereços IPs'
        ordering = ['register_in']


class ElectronicEquipment(Base):
    department = models.ForeignKey(Department, on_delete=models.CASCADE, max_length=80,
                                   verbose_name='Departamento')
    equipment = models.CharField(max_length=80, verbose_name='Identificação')
    type = models.CharField(max_length=10, choices=EQUIPMENT_TYPE_CHOICES, verbose_name='Tipo')
    ip = models.OneToOneField(IP, blank=True, null=True, on_delete=models.CASCADE, verbose_name='IP')
    warning = models.TextField(blank=True, verbose_name='Observações')

    def __str__(self):
        return self.equipment

    class Meta:
        verbose_name = 'Equipamento'
        verbose_name_plural = 'Equipamentos'
        ordering = ['register_in']

equipments/forms.py
from django.forms import ModelForm

from equipments.models import IP, ElectronicEquipment


class IpForm(ModelForm):
    class Meta:
        model = IP
        fields = ['ips_address', 'activated']


class ElectronicEquipmentForm(ModelForm):
    class Meta:
        model = ElectronicEquipment
        fields = '__all__'

ip/forms.py
from django.forms import ModelForm

from ip.models import IP, ElectronicEquipment


class IpForm(ModelForm):
    class Meta:
        model = IP
        fields = ['ips_address', 'activated']


class ElectronicEquipmentForm(ModelForm):
    class Meta:
        model = ElectronicEquipment
        fields = '__all__'

equipments/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render, redirect
from django.urls import reverse_lazy

from equipments.forms import IpForm, ElectronicEquipmentForm
from equipments.models import IP, ElectronicEquipment
from django.views import generic


class IpListView(generic.ListView):
    model = IP
    template_name = 'ip/list_ips.html'

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context['list_all_ip'] = IP.objects.filter(activated=True)
        return context


def disabled_IP_list(request):
    template_name = 'ip/list_ips.html'
    list_all_ip = IP.objects.filter(activated=False)
    context = {'list_all_ip': list_all_ip}
    return render(request, template_name, context)


def list_all_ip(request):
    template_name = 'ip/list_ips.html'
    list_all_ip = IP.objects.all()
    context = {'list_all_ip': list_all_ip}
    return render(request, template_name, context)


class IpDetailView(generic.DeleteView):
    model = IP
    template_name = 'ip/detail.html'
    context_object_name = 'equipments'


def register_ip(request):
    if request.method == "POST":
        form = IpForm(request.POST)
        if form.is_valid():
            ip = form.save(commit=False)
            ip.save()
            return redirect('ip:active_list')
    else:
        form = IpForm()
    return render(request, 'ip/register.html', {'form': form})


class IpDeleteView(generic.DeleteView):
    model = IP
    template_name = 'ip/delete.html'
    success_url = reverse_lazy('equipments:active_list')


class IpUpdateView(generic.UpdateView):
    model = IP
    template_name = 'ip/update.html'
    fields = '__all__'


class ElectronicEquipmentListView(generic.ListView):
    template_name = 'equipment/equipments_list.html'
    model = ElectronicEquipment
    context_object_name = 'equipments'


class ElectronicEquipmentEditView(generic.UpdateView):
    model = ElectronicEquipment
    fields = '__all__'
    template_name = 'equipment/equipments_edit.html'
    success_url = reverse_lazy('equipments:equipments')


class ElectronicEquipmentCreateView(generic.CreateView):
    form_class = ElectronicEquipmentForm
    template_name = 'equipment/equipments_edit.html'
    success_url = reverse_lazy('equipments:equipments')


class ElectronicEquipmentDeleteView(generic.DeleteView):
    model = ElectronicEquipment
    template_name = 'equipment/equipment_delete.html'
    success_url = reverse_lazy('equipments:equipments')


class ElectronicEquipmentDetailView(generic.DetailView):
    model = ElectronicEquipment
    context_object_name = 'equipments'
    template_name = 'equipment/equipments_detail.html'

ip/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render, redirect
from django.urls import reverse_lazy

from ip.forms import IpForm, ElectronicEquipmentForm
from ip.models import IP, ElectronicEquipment
from django.views import generic


class IpListView(generic.ListView):
    model = IP
    template_name = 'ip/list_ip.html'

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context['list_all_ip'] = IP.objects.filter(activated=True)
        return context


def disabled_IP_list(request):
    template_name = 'ip/list_ip.html'
    list_all_ip = IP.objects.filter(activated=False)
    context = {'list_all_ip': list_all_ip}
    return render(request, template_name, context)


def register_ip(request):
    if request.method == "POST":
        form = IpForm(request.POST)
        if form.is_valid():
            ip = form.save(commit=False)
            ip.save()
            return redirect('ip:list')
    else:
        form = IpForm()
    return render(request, 'ip/register.html', {'form': form})


class IpDeleteView(generic.DeleteView):
    model = IP
    template_name = 'ip/delete.html'
    success_url = reverse_lazy('ip:list')


class IpDetailView(generic.DeleteView):
    model = IP
    template_name = 'ip/detail.html'
    context_object_name = 'ip'


class IpUpdateView(generic.UpdateView):
    model = IP
    template_name = 'ip/update.html'
    fields = '__all__'


class ElectronicEquipmentListView(generic.ListView):
    template_name = 'department/equipments_list.html'
    model = ElectronicEquipment
    context_object_name = 'equipments'


class ElectronicEquipmentEditView(generic.UpdateView):
    model = ElectronicEquipment
    fields = '__all__'
    template_name = 'department/equipments_edit.html'
    success_url = reverse_lazy('ip:equipments')


class ElectronicEquipmentCreateView(generic.CreateView):
    form_class = ElectronicEquipmentForm
    template_name = 'department/equipments_edit.html'
    success_url = reverse_lazy('ip:equipments')

equipments/templates/ip/delete.html
{% extends 'base.html' %}
{% block content %}
<form method="post">
    {% csrf_token %}
    <div class="alert alert-danger d-flex align-items-center" role="alert">
        <i class="fas fa-exclamation-triangle text-warning m-2 fa-2x"></i>
        <div>
            <p>Tem certeza que deseja deletar o IP: <span class="fw-bold">{{object.ips_address}}</span>?</p>
        </div>
    </div>
    <button type="submit" class="btn btn-outline-primary">Confirmar</button>
    <a href="{% url 'ip:active_list' %}" class="btn btn-outline-danger">Cancelar</a>
</form>
{% endblock content %}

equipments/templates/ip/detail.html
{% extends 'base.html' %}
{% block content %}
<table class="table table-bordered text-center">
    <thead>
    <tr>
        <th scope="col">ID</th>
        <th scope="col">IP</th>
        <th scope="col">Cadastrado</th>
        <th scope="col">Atualizado</th>
        <th scope="col">Status</th>
    </tr>
    </thead>
    <tbody>
    <tr>
        <th scope="row">{{equipments.id}}</th>
        <td>{{equipments.ips_address}}</td>
        <td>{{equipments.register_in|date}}</td>
        <td>{{equipments.updated_in|date}}</td>
        {% if equipments.activated %}
        <td>Ativo</td>
        {% else %}
        <td>Inativo</td>
        {% endif %}
    </tr>
    </tbody>
</table>
<a href="{% url 'ip:edit' equipments.pk %}" type="button" class="btn btn-outline-warning">Editar</a>
<a href="{% url 'ip:active_list' %}" class="btn btn-outline-primary">Voltar</a>
{% endblock content %}

equipments/templates/ip/list_ip.html
{% extends 'base.html' %}
{% block content %}
<table class="table table-bordered text-center">
    <thead>
    <tr>
        <th scope="col">ID</th>
        <th scope="col">IP</th>
        <th scope="col">Ação</th>
    </tr>
    </thead>
    <tbody>
    {% for ip in list_all_ip %}
    <tr>
        <th scope="row">{{ip.id}}</th>
        <td>{{ip.ips_address}}</td>
        <td>
            <div class="btn-group" role="group" aria-label="Basic example">
                <a href="{{ ip.get_absolute_url }}" class="btn btn-success"><i class="fas fa-eye"></i></a>
                <a href="{% url 'ip:edit' ip.pk %}" class="btn btn-primary"><i class="far fa-edit"></i></a>
                <a href="{% url 'ip:delete' ip.id %}" class="btn btn-danger"><i class="fas fa-trash-alt"></i></a>
            </div>
        </td>
        {% endfor %}
    </tr>
    </tbody>
</table>
{% endblock content %}

equipments/templates/ip/list_ips.html
{% extends 'base.html' %}
{% block content %}
<div class="btn-group mb-2" role="group">
    <a href="{% url 'ip:register' %}" type="button" class="btn btn-primary"><i class="fas fa-plus"></i>Adicionar</a>
</div>
<table class="table table-bordered text-center">
    <thead>
    <tr>
        <th scope="col">ID</th>
        <th scope="col">IP</th>
        <th scope="col">Cadastrado</th>
        <th scope="col">Atualizado</th>
        <th scope="col">Status</th>
        <th scope="col">Ação</th>
    </tr>
    </thead>
    <tbody>
    {% for ip in list_all_ip %}
    <tr>
        <th scope="row">{{ip.id}}</th>
        <td>{{ip.ips_address}}</td>
        <td>{{ip.register_in|date}}</td>
        <td>{{ip.updated_in|date}}</td>
        {% if ip.activated %}
        <td>Ativo</td>
        {% else %}
        <td>Inativo</td>
        {% endif%}
        <td>
            <div class="btn-group" role="group" aria-label="Basic example">
                <a href="{{ ip.get_absolute_url }}" class="btn btn-success"><i class="fas fa-eye"></i></a>
                <a href="{% url 'ip:edit' ip.pk %}" class="btn btn-primary"><i class="far fa-edit"></i></a>
                <a href="{% url 'ip:delete' ip.id %}" class="btn btn-danger"><i class="fas fa-trash-alt"></i></a>
            </div>
        </td>
        {% endfor %}
    </tr>
    </tbody>
</table>
{% endblock content %}

equipments/templates/ip/register.html
{% extends 'base.html' %}
{% load bootstrap5 %}
{% block content %}
<form method="post">
    {% csrf_token %}
    {% bootstrap_form form %}
    <button type="submit" class="btn btn-outline-primary">Confirmar</button>
    <a href="{% url 'ip:active_list' %}" class="btn btn-outline-danger">Cancelar</a>
</form>
{% endblock content %}

equipments/templates/ip/update.html
{% extends 'base.html' %}
{% load bootstrap5 %}
{% block content %}
<form method="post">
    {% csrf_token %}
    {% bootstrap_form form %}
    <button type="submit" class="btn btn-outline-primary">Confirmar</button>
    <a href="{% url 'ip:active_list' %}" class="btn btn-outline-danger">Cancelar</a>
</form>
{% endblock content %}